<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>Yogurting.Tests.VerifyBootyBox</StartupObject>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="VerifyBootyBox.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Yogurting.Core\Yogurting.Core.csproj" />
    <ProjectReference Include="..\src\Yogurting.Data\Yogurting.Data.csproj" />
    <ProjectReference Include="..\src\Yogurting.Server\Yogurting.Server.csproj" />
  </ItemGroup>
</Project>
